#!/usr/bin/env python3
"""Generate assets/js/data.js straight from the master spreadsheet.

Run this again whenever the master xlsx changes:
    python3 scripts/gen-teams.py "/path/to/KTFCSA App Base MASTER Data.xlsx"

Values are copied verbatim. Numbers stored as numbers, text left as text.
"""
import datetime
import json
import pathlib
import re
import sys
import xml.etree.ElementTree as ET
import zipfile

NS = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"
SRC = sys.argv[1] if len(sys.argv) > 1 else str(
    pathlib.Path.home() / "Downloads" / "KTFCSA App Base MASTER Data.xlsx"
)
OUT = pathlib.Path(__file__).resolve().parent.parent / "assets" / "js" / "data.js"


def read_rows(path):
    z = zipfile.ZipFile(path)
    shared = []
    root = ET.fromstring(z.read("xl/sharedStrings.xml"))
    for si in root.findall(NS + "si"):
        shared.append("".join(t.text or "" for t in si.iter(NS + "t")))
    sheet = ET.fromstring(z.read("xl/worksheets/sheet1.xml"))
    rows = []
    for row in sheet.iter(NS + "row"):
        cells = {}
        for c in row.findall(NS + "c"):
            col = re.match(r"[A-Z]+", c.get("r")).group()
            v = c.find(NS + "v")
            if v is None:
                inline = c.find(NS + "is")
                val = "".join(x.text or "" for x in inline.iter(NS + "t")) if inline is not None else ""
            elif c.get("t") == "s":
                val = shared[int(v.text)]
            else:
                val = v.text or ""
            if val != "":
                cells[col] = val
        if cells:
            rows.append(cells)
    return rows


def as_date(v):
    try:
        return (datetime.date(1899, 12, 30) + datetime.timedelta(days=float(v))).isoformat()
    except (TypeError, ValueError):
        return v or ""


def as_time(v):
    try:
        mins = round(float(v) * 24 * 60)
        return "%02d:%02d" % (mins // 60, mins % 60)
    except (TypeError, ValueError):
        return v or ""


def as_num(v):
    """Return an int/float when the cell is numeric, otherwise the original text."""
    if v in (None, ""):
        return None
    try:
        f = float(v)
        return int(f) if f == int(f) else f
    except (TypeError, ValueError):
        return v


def slug(name):
    s = name.lower().replace("'", "").replace("&", "and")
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


rows = read_rows(SRC)
header = rows[0]
teams = []

for cells in rows[1:]:
    if "A" not in cells:
        continue
    r = {header.get(k, k): v for k, v in cells.items()}
    coords = (r.get("Coordinates (Lat, Long)") or "").split(",")
    lat = float(coords[0].strip()) if len(coords) == 2 else None
    lng = float(coords[1].strip()) if len(coords) == 2 else None
    teams.append({
        "id": slug(r["Team Name"]),
        "name": r["Team Name"],
        "nickname": r.get("Team Nickname", ""),
        "stadium": r.get("Ground Name", ""),
        "postcode": r.get("Postcode", ""),
        "capacity": as_num(r.get("Ground Capacity")),
        "lat": lat,
        "lng": lng,
        "distanceMiles": as_num(r.get("Miles from Latimer Park")),
        "homeDate": as_date(r.get("Fixture Date (Home)")),
        "homeKickoff": as_time(r.get("Kick-off (Home)")),
        "awayDate": as_date(r.get("Fixture Date (Away)")),
        "awayKickoff": as_time(r.get("Kick-off (Away)")),
        "adultPrice": as_num(r.get("Adult Price")),
        "concessionPrice": as_num(r.get("Concession Price")),
        "youthPrice": as_num(r.get("Youth Price")),
        "youthRange": r.get("Youth Range", ""),
        "childPrice": as_num(r.get("Child Price")),
        "childRange": r.get("Child Range", ""),
        "ticketNotes": r.get("Ticket Notes", ""),
        "carPark": r.get("Nearest Car Park", ""),
        "carParkPostcode": r.get("Car Park Postcode", ""),
        "parkingHourly": r.get("Average Hourly Parking Cost", ""),
        "parkingDaily": r.get("Estimated Daily Parking Rate", ""),
        "pub": r.get("Nearby Pub", ""),
        "pubPostcode": r.get("Pub Postcode", ""),
        "fact": r.get("Factoid about Opposition", ""),
    })

teams.sort(key=lambda t: t["name"])
body = ",\n".join("  " + json.dumps(t, ensure_ascii=False) for t in teams)

OUT.write_text(
    "/* Generated by scripts/gen-teams.py from the master spreadsheet. Do not edit by hand. */\n"
    "export const KTFC = {\n"
    '  name: "Kettering Town",\n'
    '  ground: "Latimer Park",\n'
    '  street: "Polwell Lane, Burton Latimer",\n'
    '  town: "Kettering",\n'
    '  postcode: "NN15 5PS",\n'
    "  lat: 52.366747,\n"
    "  lng: -0.690147,\n"
    "  /* Confirmed from the club's own ticketing, 2026/27. */\n"
    "  adultPrice: 15,\n"
    '  adultRange: "18\\u201360",\n'
    "  concessionPrice: 10,\n"
    '  concessionRange: "60+ or NUS card",\n'
    "  youthPrice: 5,\n"
    '  youthRange: "11\\u201318, secondary school age",\n'
    "  childPrice: 2,\n"
    '  childRange: "Under 11",\n'
    "};\n\n"
    "export const TEAMS = [\n" + body + "\n];\n",
    encoding="utf-8",
)
print("Wrote %s (%d clubs)" % (OUT, len(teams)))
